### PR TITLE
Add autocomplete to Settings

### PR DESCRIPTION
**Pull request by usernamehw**
AFAIK there's no support for `definitions` in contributed configuration, so there's some amount of copy/paste involved.

demo

### CODE REVIEW

**Comment by usernamehw** [comment]
Ugh ... missed one syntax:

```javascript
"highlight.regexes": {
  "(//TODO)(:)": { // A regex will be created from this string, don't forget to double escape it
    "regexFlags": "g", // Flags used when building this regex
    "filterLanguageRegex": "markdown", // Apply only if current file's language matches this regex. Requires double escaping
    "filterFileRegex": ".*\\.ext", // Apply only if the current file's path matches this regex. Requires double escaping
    "decorations": [ // Decoration options to apply to the capturing groups
      { "color": "yellow" }, // Decoration options to apply to the first capturing group, in this case "//TODO"
      { "color": "red" } // Decoration options to apply to the second capturing group, in this case ":"
    ]
  }
}
```

Will fix in the next commit.

**Comment by fabiospampinato** [comment]
@usernamehw Thanks for the PR but this seems like a nightmare to maintain, just reasoning about it is challenging give that we are talking about ~1500 lines of code/configuration. But I also think we should have better autocomplete support, perhaps we could make a script that updates the configuration object inside `package.json` in a way that we can actually reason about said script and update it when new decorations are supported? 🤔

**Comment by usernamehw** [comment]
Just found this parser: https://github.com/YousefED/typescript-json-schema

If everything goes as planned then I will update the PR with generated version this week and post the script itself by comment and not as a commit.

**Comment by usernamehw** [comment]
@fabiospampinato updated PR with generated version.

Script:
```typescript
import * as fs from 'fs';
import { resolve } from 'path';

import * as TJS from 'typescript-json-schema';
import * as https from 'https';

// Fetch the latest definitions
const file = fs.createWriteStream('vscode.d.ts');
https.get("https://raw.githubusercontent.com/Microsoft/vscode/master/src/vs/vscode.d.ts", (response) => {
    response.pipe(file);
    file.on('close', generateSchema);
});

function generateSchema() {
    const settings: TJS.PartialArgs = {
        ref: false// No support of `$ref`/`definitions` in vscode contributed settings
    };
    const compilerOptions: TJS.CompilerOptions = {
        strictNullChecks: true
    }
    const program = TJS.getProgramFromFiles([resolve('vscode.d.ts')], compilerOptions);
    const generator = TJS.buildGenerator(program, settings);

    if (!generator) {
        console.log('Something went wrong, `generator` === null');
        return;
    }
    const usefulDescriptions = ['light', 'dark', 'before', 'after', 'rangeBehavior', 'isWholeLine', 'gutterIconPath', 'gutterIconSize', 'contentText', 'contentIconPath'];

    const rangeBehaviorDescriptions = ['OpenOpen', 'ClosedClosed', 'OpenClosed', 'ClosedOpen'];
    const overviewRulerLaneDescriptions = {
        '1': 'Left',
        '2': 'Center',
        '4': 'Right',
        '7': 'Full'
    };
    const decoration = generator.getSchemaForSymbol("DecorationRenderOptions");
    delete decoration.$schema;

    forEachRecursive(decoration, (item: any, parentKey: string) => {
        if (isObject(item) && item.description) {
            // Most of the descriptions are garbage: `CSS styling property that will be applied to text enclosed by a decoration.`
            if (!usefulDescriptions.includes(parentKey)) {
                delete item.description;
            }
            // EnumDescriptions is not a standard json schema and cannot be generated
            if (parentKey === 'rangeBehavior') {
                const enums = item.enum as Array<string>;
                item.enumDescriptions = enums.map((e: any) => rangeBehaviorDescriptions[e]);
            } else if (parentKey === 'overviewRulerLane') {
                const enums = item.enum as Array<string>;
                // @ts-ignore
                item.enumDescriptions = enums.map((e: any) => overviewRulerLaneDescriptions[e]);
            }
        }
    });

    const arrayOfDecorations = {
        "type": "array",
        "items": {
            "type": "object",
            "properties": decoration.properties
        }
    };

    const result: any = {};
    result['highlight.decorations'] = {
        "type": "object",
        "description": "Default decorations from which all others inherit from",
        "properties": decoration.properties
    };
    result['highlight.regexes'] = {
        "type": "object",
        "description": "Object mapping regexes to an array of decorations to apply to the capturing groups",
        "default": {},
        "patternProperties": {
            "^.*$": {
                "oneOf": [
                    arrayOfDecorations,
                    {
                        "type": "object",
                        "properties": {
                            "regexFlags": {
                                "type": "string",
                                "description": "Flags used when building the regexes",
                                "default": "gi"
                            },
                            "filterLanguageRegex": {
                                "type": "string",
                                "description": "Apply only if current file's language matches this regex. Requires double escaping"
                            },
                            "filterFileRegex": {
                                "type": "string",
                                "description": "Apply only if the current file's path matches this regex. Requires double escaping"
                            },
                            "decorations": arrayOfDecorations
                        }
                    }
                ]
            }
        }
    }

    fs.writeFileSync('./generated.json', JSON.stringify(result, undefined, '  '), 'utf8');
}
// ================================================================================
function forEachRecursive(items: any, func: any, parentKey?: string) {
    if (Array.isArray(items)) {
        for (const item of items) {
            forEachRecursive(item, func, parentKey);
        }
    } else if (isObject(items)) {
        for (const key in items) {
            // `anyOf` choice is irrelevant and will confuse the users by suggesting passing objects (Uri, ThemeColor)
            if (key === 'anyOf') {
                delete items.anyOf;
                items.type = 'string';
            }
            forEachRecursive(items[key], func, key);
        }
        func(items, parentKey);
    }
}
function isObject(item: any) {
    return typeof item === 'object' && item !== null;
}
```

**Comment by fabiospampinato** [comment]
Good, thanks. Could you commit the script too? Perhaps make it accessible via an npm script too, so that we can run that easily before new releases.

**Pull request closed without merging**
