### PR TITLE
PR to fix flickering and improve overall performance while typing 

### PR DESCRIPTION
**Pull request by alexwall**
This fixes are related to 

https://github.com/fabiospampinato/vscode-highlight/issues/105 and 
potentially to https://github.com/Microsoft/vscode/issues/50415

This PR contains:

- The fix of the flickering issue on large files 
- A new feature (delayDecoration) for performance/efficiency optimisation while typing fast
- A fix for a currently not documented bug which occurs in situation with background decoration of a single "@tag" in a line

### CODE REVIEW

**Comment by fabiospampinato** [comment]
If I'm understanding it correctly this PR adds a `decorationDelay` option and nothing else?

If so can you:

1. Revert all the changes that don't do anything, like the following seems basically unchanged, the `Changes.decorate` function got deleted but I don't like that as I don't see the point of it.

   Screen Shot 2023-01-19 at 18 24 14

2. Revert changes that are out of scope, like updating the version number.

3. Can you also implement this with _.debounce from lodash? The way you implemented it seem verbose (we can just use lodash) and slightly not ideal perhaps (debouncing seems more appropriate).

4. Can you lower the default interval to like 25ms?

**Comment by alexwall** [comment]
1. I didn't get the idea of a separate decorate method in this specific case. Especially if you want to pass through addition parameters like `contentChanges` to the underlying methods. That created unnecessary effort to adjust each function signature. This is the reason why I've simplified that. But no problem, I'll undo it  
2. Check, will do
3. Ok
4. Yes

**Comment by alexwall** [comment]
Using _.debounce has a different behaviour. 
```typescript 
    let debounce_decoration = _.debounce(function () {
      Decorator.decorate(doc);
    }, Decorator.config.decorationDelay);

    debounce_decoration()
```
I've tried this implementation, it just delay each keystroke and processes ALL keystroke later.
I guess this is due to the fact, that each keystroke initialise each own instance of `debounce_decoration`.

My implementation has a different behaviour/goal. The goal is 
- If a keystroke occurs, a decoration update is scheduled and waits a specific time (`decorationDelay`) before triggering just ONE decoration update.  

To be honest, I have no idea how to implement the same behaviour with `_.debounce`. If you have an idea, feel free. Otherwise I'd appreciate if you just use my implementation. Thanks

**Comment by alexwall** [comment]
@fabiospampinato I have adjusted the PR regarding your change requests. Do you see any other obstacles to merging the changes?

**Comment by alexwall** [comment]
@fabiospampinato do you mind to give me an update? Is there something wrong with the PR or are you just busy?

**Comment by fabiospampinato** [comment]
@alexwall Hang tight, I'll see if I can merge this this weekend 👍 I'm kind of submerged with things to do 😅

**Comment by alexwall** [comment]
All right, thanks for your feedback 😉

**Comment by fabiospampinato** [comment]
Shipped as "highlight.minDelay" in v1.7. Thanks.

**Pull request merged**
