### PR TITLE
Fixes: re-decoration and flickering issues

### PR DESCRIPTION
**Pull request by alexwall**
@fabiospampinato I'm happy to provide this fix. 
This PR covers the situations, when a decoration gets invalid and must be removed. At the same time it avoids flickering of decoration on larger files. 

Resolves this issues:

- https://github.com/fabiospampinato/vscode-highlight/issues/109 
- https://github.com/fabiospampinato/vscode-highlight/issues/105

### CODE REVIEW

**Comment by ene-wall** [comment]
@fabiospampinato FYI: I've resolved the merge conflicts regarding the rollback (1.7.2)

**Comment by alexwall** [comment]
@fabiospampinato FYI: I've resolved the merge conflicts regarding the rollback (1.7.2)

**Comment by alexwall** [comment]
Hi @fabiospampinato, do you see any change to merge this PR soon. I patched `Highlight` locally and haven't noticed  any problems in the past two weeks. I would like to keep all my machines updated and in sync with the official extension releases and avoid manual patching.

**Comment by fabiospampinato** [comment]
Jeez I hadn't realized more than a month had passed already! 

Released as v1.7.3, let's see how it goes, if I'm understanding it it looks like it should work if vscode now diffs decorations, but I'm pretty sure I was explicitly doing it the old way because it wasn't, so let's see.

Thank you.

**Pull request merged**
